# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Nafnster' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Nafnster
  pod 'AppCenter/Crashes', '~> 1.1.0'
  pod 'AppCenter/Analytics', '~> 1.1.0'
  pod 'AppCenterReactNativeShared', '~> 1.1.0'

  

  target 'NafnsterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Nafnster-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Nafnster-tvOS

  target 'Nafnster-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
